In [4]:
# topics coverd here
# Indexing and slicing
# iterating through arrays
# Stacking together two arrays
# indexing with boolean arrays

In [5]:
import os
os.chdir('/Users/rajatpa/Documents/DS/code_basics/py/numpy')
import numpy as np

In [6]:
# Indexing and slicing
a = np.array([[6,7,8],[1,2,3],[9,3,2]])
a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [7]:
# printing the element present in 1st row and 2nd column
a[1,2]

3

In [8]:
a[0:2,2]

array([8, 3])

In [9]:
# if we want to print the last row 
a[-1]

array([9, 3, 2])

In [10]:
# printing the last row and the columns 0 and 1( as excluding 2)
a [-1,0:2]

array([9, 3])

In [11]:
# if want to print all the rows and column 1 and 2( it srats from 0,1,2 in python)
a[:,1:3]

array([[7, 8],
       [2, 3],
       [3, 2]])

In [12]:
# iterating through arrays
for row in a:
    print(row)

[6 7 8]
[1 2 3]
[9 3 2]


In [18]:
[x for x in a.flat]

[6, 7, 8, 1, 2, 3, 9, 3, 2]

In [19]:
# create numpy array with arange and reshape using same time
b = np.arange(6).reshape(3,2)
c = np.arange(6,12).reshape(3,2)
display(b,c)

array([[0, 1],
       [2, 3],
       [4, 5]])

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [20]:
# Vertical Stacking together two arrays
d = np.vstack((b,c))
d

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [21]:
# Horizantal Stacking together two arrays
e = np.hstack((b,c))
e

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [22]:
f = np.arange(30).reshape(2,15)
f

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [34]:
# if we want to split the array f in to 3 different array
g = np.hsplit(f,3)
g

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]), array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]), array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [36]:
display(g [0],g[1],g[2])

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]])

array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])

In [35]:
h = np.vsplit(f,2)
h 

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

In [37]:
display(h[0],h[1])

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [38]:
# indexing with boolean arrays
i = np.arange(12).reshape(3,4)
i

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [39]:
j = i > 4
j

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [40]:
# using one bolean array as indexing for one normal array
i[j]

array([ 5,  6,  7,  8,  9, 10, 11])

In [42]:
# we can also set the values using bolean array
i[j] = -1
i

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])