In [2]:
import os
os.chdir('/Users/rajatpa/Documents/DS/code_basics/py/numpy')
import numpy as np

In [4]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [14]:
[x for x in np.nditer(a,order = 'C')]

[array(0),
 array(1),
 array(2),
 array(3),
 array(4),
 array(5),
 array(6),
 array(7),
 array(8),
 array(9),
 array(10),
 array(11)]

In [15]:
# C is for C code style
for x in np.nditer(a, order='C'):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [16]:
# F is for Fortan
for x in np.nditer(a, order='F'):
    print(x)

0
4
8
1
5
9
2
6
10
3
7
11


In [17]:
# if want to print entire column
for x in np.nditer(a, order='F',flags = ['external_loop']):
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [19]:
# if want to print entire column
for x in np.nditer(a, order='C',flags = ['external_loop']):
    print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [21]:
# if i want to iterate through my array and want to do some operation same time element wise
for x in np.nditer(a,op_flags = ['readwrite']):
    x[...] = x*x

In [22]:
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [34]:
# if we want to iterate two numpy array at the same time
# for doing this the nu
b = np.arange(3).reshape(3,1)
b

array([[0],
       [1],
       [2]])

In [35]:
for x,y in np.nditer([a,b]):
    print(x,y)

0 0
1 0
4 0
9 0
16 1
25 1
36 1
49 1
64 2
81 2
100 2
121 2
