In [1]:
import os
os.chdir('/Users/rajatpa/Documents/DS/code_basics/py/numpy/')

In [2]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib as inline

UsageError: unrecognized arguments: inline


In [3]:
# let's create a two dimensional array
a = np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [7]:
display(a.ndim,a.shape,a.dtype,a.size)

2

(3, 2)

dtype('int64')

6

In [6]:
# if we want to check the size of the element present in the numpy array
a.itemsize

8

In [9]:
b = np.array([[1,1],[2,2]],dtype='float64')
b

array([[1., 1.],
       [2., 2.]])

In [11]:
b.itemsize

8

In [12]:
c = np.array([[3,1],[3,2]],dtype='complex')
c

array([[3.+0.j, 1.+0.j],
       [3.+0.j, 2.+0.j]])

In [15]:
# creating zero value elements in the numpy array
d = np.zeros((3,4))
d

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
# creating one value elements in the numpy array
e = np.ones((4,4))
e

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
# the normal python ranage is arange in numpy
f = np.arange(1,10)
f

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
# If we want to generate some number similar kind of range function but that should be linearly spaced.
g = np.linspace(1,5,10)
g

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [24]:
a.shape

(3, 2)

In [25]:
# if we want to change the shape of the numpy array a from (3,2) to (2,3)
h = a.reshape(2,3)
h

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
# If we want to flatten the numpy array and want to convert it to single dimensional 
i = a.ravel()
i

array([1, 2, 3, 4, 5, 6])

In [28]:
a.sum()

21

In [29]:
# axis = 0 is column waise and axis = 1 
a.sum(axis=0)

array([ 9, 12])

In [30]:
a.sum(axis=1)

array([ 3,  7, 11])

In [31]:
# if we want to derive the squareroot of an numpy array
j = np.sqrt(a)
j

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [32]:
# if we want the standard deviation of a
k = np.std(a)
k

1.707825127659933

In [34]:
# addition operation of numpy array
x = np.array([[1,2],[4,5]])
x

array([[1, 2],
       [4, 5]])

In [35]:
y = np.array([[2,2],[3,3]])
y

array([[2, 2],
       [3, 3]])

In [36]:
z = x + y
z

array([[3, 4],
       [7, 8]])

In [37]:
# we want to do the dot product ( matrix operation)
D = a.dot(b)
D

array([[ 5.,  5.],
       [11., 11.],
       [17., 17.]])